import type { Metadata } from "next";

import "./globals.css";

import StoreProvider from "./provider";
import InfoShowCase from "./components/InfoShowcase/InfoShowCase";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"

    >
      <StoreProvider>
        <body className="min-h-full  font-primary ">
          <InfoShowCase/>
          <Header/>
          {children}
          <Footer/>
        </body>
      </StoreProvider>
    </html>
  );
}
